<div id="custom-form">
	<form class="form contact" action=" <?= $block->getFormAction();?>" id="custom-contact-form" method="post" data-hasrequired=" <?= __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
		<input type="hidden" name="cproduct_id" id="cproduct_id" value="0" />
		<fieldset class="fieldset">
			<legend class="legend">
				<span>
					<?= __("Custom Contact Form") ?>
				</span>
			</legend>
			<br />
			<div class="field name required">
				<label class="label" for="name">
					<span>
						<?= __('First Name') ?>
					</span>
				</label>
				<div class="control">
					<input name="firstname" id="name" title="<?= __('First Name') ?>" class="input-text" type="text" data-validate="{required:true}"/>
				</div>
			</div>
			<div class="field name required">
				<label class="label" for="name">
					<span>
						<?= __('Last Name') ?>
					</span>
				</label>
				<div class="control">
					<input name="lastname" id="name" title="<?= __('Last Name') ?>" class="input-text" type="text" data-validate="{required:true}"/>
				</div>
			</div>
			<div class="field email required">
				<label class="label" for="email">
					<span>
						<?= __('Email') ?>
					</span>
				</label>
				<div class="control">
					<input name="email" id="email" title="<?= __('Email') ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
				</div>
			</div>
			<div class="field phone required">
				<label class="label" for="phone">
					<span>
						<?= __('Phone Number') ?>
					</span>
				</label>
				<div class="control">
					<input name="phone" id="phone" title="<?= __('Phone Number') ?>" value="" class="input-text" type="text" data-validate="{required:true, 'validate-number':true, 'validate-greater-than-zero':true, 'maxlength':10}" />
				</div>
			</div>
			<div class="field comment required">
				<label class="label" for="comment">
					<span>
						<?= __('What’s on your mind?') ?>
					</span>
				</label>
				<div class="control">
					<textarea name="comment" id="comment" title="<?= __('What’s on your mind?') ?>" class="input-text" data-validate="{required:true}"></textarea>
				</div>
			</div>
		</fieldset>
		<div class="actions-toolbar">
			<div class="primary">
				<input type="hidden" name="hideit" id="hideit" value="" />
				<button type="submit" title="
					<?= __('Submit') ?>" class="action submit primary" id="custom_btn">
					<span>
						<?= __('Submit') ?>
					</span>
				</button>
			</div>
		</div>
	</form>
</div>